# Generated by Django 3.2 on 2021-05-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
