# Generated by Django 3.2 on 2021-05-26 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teacher_date_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполенно'),
        ),
        migrations.CreateModel(
            name='MedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_medreview', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('medcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medcenter_medreview', to=settings.AUTH_USER_MODEL, verbose_name='Вет клиника')),
            ],
        ),
    ]
