# Generated by Django 3.2 on 2021-06-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210527_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
