# Generated by Django 3.2 on 2021-06-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teacher_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tegs',
            field=models.TextField(blank=True, null=True, verbose_name='Теги'),
        ),
    ]
