# Generated by Django 3.2 on 2021-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_teacher_tegs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='phone',
            field=models.CharField(default='7776665544', max_length=11, verbose_name='Номер без (+7)'),
        ),
    ]
