# Generated by Django 3.2 on 2021-06-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_bids_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заявки'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='До'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=500, verbose_name='Специализация'),
        ),
    ]
