# Generated by Django 3.2 on 2021-06-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210607_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='phone',
            field=models.CharField(default='7776665544', max_length=11, verbose_name='Номер без (+7)'),
        ),
    ]
