# Generated by Django 3.2 on 2021-06-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_medicalcenter_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='someInfo',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
