# Generated by Django 3.2 on 2021-06-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_bids_someinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата заявки'),
        ),
    ]
