# Generated by Django 3.2 on 2021-06-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_completedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Закончено'),
        ),
    ]
