# Generated by Django 3.2 on 2021-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_completedtask_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='tegs',
            field=models.TextField(blank=True, null=True, verbose_name='Теги'),
        ),
    ]
