# Generated by Django 3.2 on 2021-06-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_medicalcenter_tegs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заявки'),
        ),
    ]
