# Generated by Django 3.2 on 2021-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_bids_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='num_page_see',
            field=models.IntegerField(default=0, verbose_name='Сколько раз посмотрели страницу'),
        ),
    ]
