# Generated by Django 3.2 on 2021-06-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_teacher_num_page_see'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='date_show_phone',
            field=models.DateTimeField(auto_now=True, verbose_name='Время когда врач посмотрел номер'),
        ),
        migrations.AddField(
            model_name='bids',
            name='show_phone',
            field=models.BooleanField(default=False, verbose_name='Просмотрел врач номер'),
        ),
    ]
