# Generated by Django 3.2 on 2021-06-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210610_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='О клинике'),
        ),
    ]
