# Generated by Django 3.2 on 2021-06-18 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_medicalcenter_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcenter',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
