# Generated by Django 3.2 on 2021-06-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210618_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_med',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_is_med_foreign', to='main.medicalcenter', verbose_name='Мед центр'),
        ),
    ]
