# Generated by Django 3.2 on 2021-06-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210618_1911'),
        ('main', '0029_teacher_is_med'),
    ]

    operations = [
    ]
