# Generated by Django 3.2 on 2021-06-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_medicalcenter_this_is'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='service_photo')),
                ('name', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('tegs', models.TextField(blank=True, null=True, verbose_name='Теги')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='services',
            field=models.ManyToManyField(to='main.Services', verbose_name='К какой услуге относится'),
        ),
    ]
