# Generated by Django 3.2 on 2021-06-24 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210623_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.ImageField(blank=True, upload_to='service_photo', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])]),
        ),
    ]
