# Generated by Django 3.2 on 2021-06-24 12:52

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_services_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.FileField(blank=True, upload_to='service_photo', validators=[main.validators.validate_file_extension]),
        ),
    ]
