# Generated by Django 3.2 on 2021-06-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210628_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcenter',
            name='this_is',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Вет клиника'), (2, 'Зоомагазин'), (3, 'Аптека'), (4, 'Кинолог'), (5, 'Грумеры'), (6, 'Приют')], default=1),
        ),
    ]
