# Generated by Django 3.2 on 2021-06-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_teacher_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='district',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ауэзовский'), (2, 'Медеуский'), (3, 'Бостандыкский'), (4, 'Алмалинский'), (5, 'Жетысуский')], default=1),
        ),
    ]
