# Generated by Django 3.2 on 2021-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_medicalcenter_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcenter',
            name='district',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ауэзовский'), (2, 'Медеуский'), (3, 'Бостандыкский'), (4, 'Алмалинский'), (5, 'Жетысуский'), (6, 'Турксибский'), (7, 'Алатауский'), (8, 'Наурызбайский')], default=1),
        ),
    ]
