# Generated by Django 3.2 on 2021-07-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210702_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcenter',
            name='phone2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер без (+7)'),
        ),
        migrations.AlterField(
            model_name='medicalcenter',
            name='phone3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер без (+7)'),
        ),
    ]
