# Generated by Django 3.2 on 2021-07-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20210702_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='phone2_comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Комментарий к номеру'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='phone3_comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Комментарий к номеру'),
        ),
    ]
