# Generated by Django 3.2 on 2021-07-05 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20210702_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='phone',
            field=models.CharField(default='7776665544', max_length=12, verbose_name='Номер без (+7)'),
        ),
        migrations.CreateModel(
            name='MedicalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medicalcenter', verbose_name='Мед центр')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='med_photo')),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medicalcenter', verbose_name='Мед центр')),
            ],
        ),
    ]
