# Generated by Django 3.2 on 2021-09-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_medicalcenter_num_phone_see'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='cht',
            field=models.BooleanField(default=True, verbose_name='Четверг'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='pn',
            field=models.BooleanField(default=True, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='pt',
            field=models.BooleanField(default=True, verbose_name='Пятница'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='sb',
            field=models.BooleanField(default=False, verbose_name='Суббота'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='sr',
            field=models.BooleanField(default=True, verbose_name='Среда'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='vs',
            field=models.BooleanField(default=False, verbose_name='Воскресенье'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='vt',
            field=models.BooleanField(default=True, verbose_name='Вторник'),
        ),
        migrations.AlterField(
            model_name='medicalcenter',
            name='phone',
            field=models.CharField(default='7776665544', max_length=12, verbose_name='Номер без (+7)'),
        ),
        migrations.AlterField(
            model_name='medicalcenter',
            name='phone2',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер без (+7)'),
        ),
        migrations.AlterField(
            model_name='medicalcenter',
            name='phone3',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер без (+7)'),
        ),
        migrations.AlterField(
            model_name='medicalcenter',
            name='photo',
            field=models.ImageField(blank=True, default='med_photo/med_default.png', upload_to='med_photo'),
        ),
    ]
