# Generated by Django 3.2 on 2021-05-27 11:13

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        #(<snip>)
    ]

    operations = [
        UnaccentExtension()
    ]
